export { default as SvgSprite } from "./sprite";
export { default as Icon } from "@/components/icons/icon";

export const ICON_IDS = {
  add: "icon-add",
  arrowDown: "icon-arrow-down",
  arrowLeft: "icon-arrow-left",
  arrowRight: "icon-arrow-right",
  arrowUp: "icon-arrow-up",
  back: "icon-back",
  badgePercent01: "icon-badge-percent-01",
  bankSavings: "icon-bank-savings",
  briefcase: "icon-briefcase",
  calender: "icon-calender",
  chartBar02: "icon-chart-bar-02",
  checkMark: "icon-check-mark",
  clipboardList01: "icon-clipboard-list-01",
  close: "icon-close",
  coinsSolid: "icon-coins-solid",
  deleteFriend: "icon-delete-friend",
  dropdown: "icon-dropdown",
  eyeOpen: "icon-eye-open",
  filter: "icon-filter",
  galaxy01: "icon-galaxy-01",
  handshake: "icon-handshake",
  home: "icon-home",
  loan: "icon-loan",
  menu: "icon-menu",
  more: "icon-more",
  notification: "icon-notification",
  npLoan: "icon-np-loan",
  npMoney: "icon-np-money",
  piggyBank01: "icon-piggy-bank-01",
  sack01: "icon-sack-01",
  search: "icon-search",
  settlements: "icon-settlements",
  signOut: "icon-sign-out",
  slidersH01: "icon-sliders-h-01",
  spinner: "icon-spinner",
  tire: "icon-tire",
  transaction: "icon-transaction",
  user: "icon-user",
  userNp: "icon-user-np-check",
  userCheck01: "icon-user-check-01",
  userCog01: "icon-user-cog-01",
  userTimes01: "icon-user-times-01",
  users: "icon-users",
  users01: "icon-users-01",
  usersOultine: "icon-users-outline",
  usersOultine01: "icon-users-outline-01",
} as const;

export type IconName = (typeof ICON_IDS)[keyof typeof ICON_IDS];
